[Xorg_inputproto]
git-tree-sha1 = "e9e0aa1c1fb69e785ff331abf85ba5a16d11f804"

    [[Xorg_inputproto.download]]
    sha256 = "f32e53db64b7fa42fc908b513e4f5a2282d6f66dc943bfe6ddbd5de5a6e0fbe2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.3+0/Xorg_inputproto.v2.3.3.any.tar.gz"
