[[Xorg_inputproto]]
arch = "armv7l"
git-tree-sha1 = "b9708231b1c8ef5ffa00a32b66bd85fe2f923b1e"
libc = "glibc"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "ca2e58f50ef80255554fafe32b4ccfcea4c76294d67c01a138bcd97879df2551"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_inputproto]]
arch = "i686"
git-tree-sha1 = "134e616f5d2ea60852a5c3cce5ed1d49a59f5d7a"
libc = "musl"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "3bcd1a6da996ac9db7a12f315466252870daec6ccff9f69141061067555408d3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.i686-linux-musl.tar.gz"
[[Xorg_inputproto]]
arch = "aarch64"
git-tree-sha1 = "0756fc9cf9194a4f0db4bc18c6cc790a1651bca5"
libc = "glibc"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "ed8d7fa7655ac33763176fd6ed040c00cd8df3cbc32429f6dd4db59cd15f6f89"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.aarch64-linux-gnu.tar.gz"
[[Xorg_inputproto]]
arch = "armv7l"
git-tree-sha1 = "74ad8759fc39224cb7fd1adcd9ca9bc6c5d64818"
libc = "musl"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "6a7c980c330c90e2d2d34d751f0cf9504b95ba16a77c710cf37ead0fedbfebc9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.armv7l-linux-musleabihf.tar.gz"
[[Xorg_inputproto]]
arch = "aarch64"
git-tree-sha1 = "d3978612539f81c625b3dbb1c7da1787d587dabc"
libc = "musl"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "77b7ca5f7b572216f678750c7b64e8a76d2ae7570544e84db67a36b433068992"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.aarch64-linux-musl.tar.gz"
[[Xorg_inputproto]]
arch = "x86_64"
git-tree-sha1 = "30e602e6b9d8e34c59260baf2669f2fa6c989f7f"
os = "freebsd"

    [[Xorg_inputproto.download]]
    sha256 = "d8951facf8ccff999158539a52fab5522ae6ba939ad7b00827e3670b51ffcabf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_inputproto]]
arch = "i686"
git-tree-sha1 = "5260ec59ada327bb32ebbe2d53bc8e1a5703c352"
libc = "glibc"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "994328c7d438d6716ec1a80f8aff386a991d93a85d3ff6b1a7ee2ec918b661f5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.i686-linux-gnu.tar.gz"
[[Xorg_inputproto]]
arch = "x86_64"
git-tree-sha1 = "d138bbe83d73b13e572f96db99155f246f8133ec"
libc = "musl"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "122d997a547f0388f15bb0021fceacf88059ce355fc2193b0150b6660b2a4cd2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.x86_64-linux-musl.tar.gz"
[[Xorg_inputproto]]
arch = "x86_64"
git-tree-sha1 = "839f3784cba2ef89bcd7f8447cd2d195b510670b"
libc = "glibc"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "9cf3344d8c3c028f951c760d212f6282704fbaf32a955eadd2eb728fba0f3915"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.x86_64-linux-gnu.tar.gz"
[[Xorg_inputproto]]
arch = "powerpc64le"
git-tree-sha1 = "7ec400db4ad07affd704a5a0d62ed7f712cd1ab4"
libc = "glibc"
os = "linux"

    [[Xorg_inputproto.download]]
    sha256 = "9bd134a6c885238b08ad0446cfdb3979e3cbcb19c0dde64eba573e6f4a33809a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_inputproto_jll.jl/releases/download/Xorg_inputproto-v2.3.2+1/Xorg_inputproto.v2.3.2.powerpc64le-linux-gnu.tar.gz"
